"""Initial

Revision ID: 1
Revises: 
Create Date: 2023-03-23 10:59:40.190956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.BigInteger(), nullable=False),
    sa.Column('price_in_dollars', sa.DECIMAL(), nullable=False),
    sa.Column('price_in_rubles', sa.DECIMAL(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_delivery_date'), 'orders', ['delivery_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_delivery_date'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
