"""Initial

Revision ID: 1
Revises: 
Create Date: 2023-03-21 13:45:53.475645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('price_in_dollars', sa.DECIMAL(), nullable=False),
    sa.Column('price_in_rubles', sa.DECIMAL(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_delivery_date'), 'records', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_records_order_number'), 'records', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_order_number'), table_name='records')
    op.drop_index(op.f('ix_records_delivery_date'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
