"""order_number unique

Revision ID: 2
Revises: 1
Create Date: 2023-03-21 16:51:08.845708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_order_number', table_name='records')
    op.create_index(op.f('ix_records_order_number'), 'records', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_order_number'), table_name='records')
    op.create_index('ix_records_order_number', 'records', ['order_number'], unique=False)
    # ### end Alembic commands ###
