"""order number -> BigInteger

Revision ID: 3
Revises: 2
Create Date: 2023-03-22 03:12:58.995345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_order_number', table_name='records')
    op.create_unique_constraint(None, 'records', ['order_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='unique')
    op.create_index('ix_records_order_number', 'records', ['order_number'], unique=False)
    # ### end Alembic commands ###
